Added Task 00 and Task 01
dzmrudak/Lesson1 pull request #2
Opened 2021-01-31 23:06 UTC by dzmrudak

2021-02-01 22:34 UTC, AntonShtabnoy requested changes

2021-02-01 22:34 UTC, AntonShtabnoy commented on src/by/rudakd/lesson1/task3/Task3.java
> +        boolean numAreDifferent = unit != doz && unit != hund && unit != thous && doz != hund && doz != thous && hund != thous;
Есть решение через 3 условия (по возможности подумать)

2021-02-01 22:34 UTC, AntonShtabnoy commented on src/by/rudakd/lesson1/task5/Task5.java
> +        else System.out.println("Круг не полностью закрывает прямоугольник");
Лучше оператор if использовать с {}

2021-02-02 19:14 UTC, dzmrudak commented on src/by/rudakd/lesson1/task5/Task5.java
> +        else System.out.println("Круг не полностью закрывает прямоугольник");
Добавил скобки

2021-02-08 00:06 UTC, merged